name: 'CI Nível 01 - Execução Manual para Trabalho de Conclusão de Disciplina - PGATS'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Execução de Testes E2E com Cypress
        run: yarn cypress run

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: cypress/reports/html/.jsons/**/*.{json,html}


